name: prokit_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  smooth_page_indicator: ^1.1.0
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  path: ^1.8.3
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/images/walkthrough/
     - assets/images/logo/
     - assets/images/actors/
     - assets/images/movieposter/
     - assets/images/genere/
     - assets/images/user/
     - assets/images/actors/andrew_garfield/
     - assets/images/actors/chris_evans/
     - assets/images/actors/emma_watson/
     - assets/images/actors/chris_hemsworth/
     - assets/images/actors/hrithik_roshan/
     - assets/images/actors/robert_downey/
     - assets/images/actors/tom_holland/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
